# caminho para um diretório com todos os pacotes
storage: ../build/local-registry/storage

auth:
  htpasswd:
    file: ./htpasswd

# uma lista de outros repositórios conhecidos com os quais podemos conversar
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    cache: true
  yarn:
    url: https://registry.yarnpkg.com
    cache: true

packages:
  '@*/*':
    # pacotes com escopo
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

  '**':
    # permite todos usuários (incluindo usuários não autenticados)
    # para ler e publicar todos os pacotes
    access: $all

    # permite todos usuários (incluindo usuários não autenticados)
    # a publicar e despublicar pacotes
    publish: $all
    unpublish: $all

    # se o pacote não estiver disponível localmente, solicitações de proxy para o registro 'yarn'
    proxy: npmjs

# configurações de log
logs:
  - { type: stdout, format: pretty, level: http }
